version: '3.4'

services:
  database:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      - "VIRTUAL_HOST=db.accounts.dev"
      - "MYSQL_DATABASE=accounts"
      - "MYSQL_USER=accounts"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
  redis:
    image: redis
    container_name: redisdb
    ports:
      - 6379:6379
  accounts.api:
    container_name: accounts.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DB_CONNECTION_NAME=Default
    ports:
      - 80:8080
    links:
      - database
      - redis
volumes:
  data:
